"""Build and query the ChromaDB vector index."""

import json
from pathlib import Path

import chromadb
from chromadb.errors import NotFoundError
from llama_index.core import Document, StorageContext, VectorStoreIndex
from llama_index.core.node_parser import SentenceSplitter
from llama_index.embeddings.openai import OpenAIEmbedding
from llama_index.vector_stores.chroma import ChromaVectorStore

from chess_tutor.config import load_settings


def load_source_metadata() -> dict[str, dict[str, str]]:
    """Load source metadata generated by the data collection pipeline."""

    metadata_by_path = {}

    for metadata_file in Path("data/raw").glob("*/metadata.json"):
        records = json.loads(metadata_file.read_text(encoding="utf-8"))

        for record in records:
            local_path = record.get("local_path")
            if local_path:
                metadata_by_path[local_path] = record

    return metadata_by_path


def load_documents(processed_dir: Path) -> list[Document]:
    """Load processed text files as LlamaIndex documents."""

    metadata_by_raw_path = load_source_metadata()
    documents = []

    for processed_file in sorted(processed_dir.glob("*/*.txt")):
        provider = processed_file.parent.name
        raw_path = str(Path("data/raw") / provider / processed_file.name)
        source_metadata = metadata_by_raw_path.get(raw_path, {})

        metadata = {
            "provider": provider,
            "source_id": source_metadata.get("source_id", processed_file.stem),
            "title": source_metadata.get("title", processed_file.stem),
            "author": source_metadata.get("author", ""),
            "license_name": source_metadata.get("license_name", ""),
            "source_url": source_metadata.get("source_url", ""),
            "file_path": str(processed_file),
        }

        documents.append(
            Document(
                text=processed_file.read_text(encoding="utf-8"),
                metadata=metadata,
            )
        )

    return documents


def estimate_tokens(text: str) -> int:
    """Estimate tokens with a simple chars-to-tokens heuristic."""

    return max(1, len(text) // 4)


def build_index() -> None:
    """Chunk processed documents, embed them, and persist them to ChromaDB."""

    settings = load_settings()

    if not settings.openai_api_key:
        raise RuntimeError("OPENAI_API_KEY is required to build the vector index.")

    processed_dir = Path(settings.processed_dir)
    persist_dir = Path(settings.persist_dir)

    documents = load_documents(processed_dir)

    if not documents:
        raise RuntimeError(f"No processed .txt files found in {processed_dir}.")

    print(f"Loaded documents: {len(documents)}")

    splitter = SentenceSplitter(
        chunk_size=settings.chunk_size,
        chunk_overlap=settings.chunk_overlap,
    )
    nodes = splitter.get_nodes_from_documents(documents)

    estimated_tokens = sum(estimate_tokens(node.get_content()) for node in nodes)
    estimated_cost = (
        estimated_tokens / 1_000_000 * settings.embedding_cost_per_1m_tokens_usd
    )

    print(f"Chunk size: {settings.chunk_size}")
    print(f"Chunk overlap: {settings.chunk_overlap}")
    print(f"Chunks to embed: {len(nodes)}")
    print(f"Estimated embedding tokens: {estimated_tokens:,}")
    print(f"Estimated embedding cost: ${estimated_cost:.4f}")

    if estimated_cost > settings.max_embedding_cost_usd:
        raise RuntimeError(
            "Estimated embedding cost is above the configured limit: "
            f"${estimated_cost:.4f} > ${settings.max_embedding_cost_usd:.2f}. "
            "Increase MAX_EMBEDDING_COST_USD if you want to proceed."
        )

    print("Building ChromaDB index. This will call the OpenAI embeddings API...")

    persist_dir.mkdir(parents=True, exist_ok=True)
    chroma_client = chromadb.PersistentClient(path=str(persist_dir))

    try:
        chroma_client.delete_collection(settings.chroma_collection_name)
    except (NotFoundError, ValueError):
        pass

    chroma_collection = chroma_client.get_or_create_collection(
        settings.chroma_collection_name
    )
    vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
    storage_context = StorageContext.from_defaults(vector_store=vector_store)
    embed_model = OpenAIEmbedding(
        model=settings.embedding_model,
        api_key=settings.openai_api_key,
    )

    VectorStoreIndex(
        nodes,
        storage_context=storage_context,
        embed_model=embed_model,
        show_progress=True,
    )

    print(f"Persisted ChromaDB index: {persist_dir}")
    print(f"Collection name: {settings.chroma_collection_name}")
